const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let state={watchlist:store.get('watchlist',APP_CONFIG.defaultWatchlist),portfolio:store.get('portfolio',APP_CONFIG.defaultPortfolio),journal:store.get('journal',[]),settings:store.get('settings',{apiKey:'',interval:0}),market:new Map(),timer:null};
const usd=n=>n==null?'—':new Intl.NumberFormat('es-ES',{style:'currency',currency:'USD',maximumFractionDigits:n<.01?8:2}).format(n);
const compact=n=>n==null?'—':new Intl.NumberFormat('es-ES',{notation:'compact',maximumFractionDigits:2}).format(n);
const pct=n=>n==null?'—':`${n>=0?'+':''}${n.toFixed(2)}%`;
function api(path){const key=state.settings.apiKey;const sep=path.includes('?')?'&':'?';return `https://api.coingecko.com/api/v3${path}${key?`${sep}x_cg_demo_api_key=${encodeURIComponent(key)}`:''}`}
async function getJSON(url){const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
function scoreCoin(c){let s=0;const mc=c.market_cap||0,v=c.total_volume||0,ratio=mc?v/mc:0,chg=c.price_change_percentage_24h||0,ath=c.ath_change_percentage||-100;if(mc>=5e6&&mc<=150e6)s+=22;else if(mc<=400e6)s+=12;if(v>=5e6)s+=20;else if(v>=2e6)s+=13;else if(v>=5e5)s+=6;s+=Math.min(22,ratio*35);if(chg>0&&chg<12)s+=14;else if(chg>=-5)s+=9;else if(chg<-15)s+=2;if(ath<-80)s+=12;else if(ath<-60)s+=8;if(APP_CONFIG.knownUniverse.includes(c.id))s+=10;return Math.max(0,Math.min(100,Math.round(s)))}
function signal(score,c){if((c.total_volume||0)<500000)return['Riesgo extremo','risk'];if(score>=78)return['Prioridad','priority'];if(score>=65)return['Vigilar','watch'];return['Esperar','wait']}
async function refreshAll(){const btn=$('#refreshBtn');btn.disabled=true;btn.textContent='Actualizando…';try{await Promise.all([loadFear(),loadMarkets()]);renderAll();$('#lastUpdate').textContent=`Actualizado ${new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`}catch(e){$('#scannerMessage').textContent=`No se pudieron actualizar todos los datos: ${e.message}. Puedes añadir una clave Demo de CoinGecko en Ajustes.`}finally{btn.disabled=false;btn.textContent='Actualizar datos'}}
async function loadFear(){try{const j=await getJSON('https://api.alternative.me/fng/?limit=1&format=json');const d=j.data[0];$('#fearValue').textContent=d.value;$('#fearLabel').textContent=d.value_classification;marketMode(+d.value)}catch{$('#fearLabel').textContent='No disponible'}}
function marketMode(f){let m='Neutral';if(f<=25)m='Risk Off';else if(f<=45)m='Precaución';else if(f>=75)m='Euforia';else if(f>=56)m='Risk On';$('#marketMode').textContent=m}
async function loadMarkets(){const ids=[...new Set([...APP_CONFIG.knownUniverse,...state.watchlist,...state.portfolio.map(p=>p.coinId),'bitcoin'])];const chunks=[];for(let i=0;i<ids.length;i+=100)chunks.push(ids.slice(i,i+100));const all=[];for(const chunk of chunks){const qs=new URLSearchParams({vs_currency:'usd',ids:chunk.join(','),order:'market_cap_desc',per_page:'100',page:'1',sparkline:'false',price_change_percentage:'1h,24h,7d'});all.push(...await getJSON(api(`/coins/markets?${qs}`)))}state.market=new Map(all.map(c=>[c.id,c]));const btc=state.market.get('bitcoin');if(btc){$('#btcPrice').textContent=usd(btc.current_price);$('#btcChange').textContent=pct(btc.price_change_percentage_24h);$('#btcChange').className=btc.price_change_percentage_24h>=0?'positive':'negative'}}
function renderScanner(){const max=+$('#maxMarketCap').value*1e6,min=+$('#minVolume').value*1e6,known=$('#knownOnly').checked;const coins=[...state.market.values()].filter(c=>c.id!=='bitcoin'&&c.market_cap<=max&&c.total_volume>=min&&(!known||APP_CONFIG.knownUniverse.includes(c.id))).map(c=>({...c,score:scoreCoin(c)})).sort((a,b)=>b.score-a.score);$('#scannerRows').innerHTML=coins.map((c,i)=>{const [label,cls]=signal(c.score,c);return `<tr><td>${i+1}</td><td><div class="coin"><img src="${c.image}" alt=""><div><b>${c.name}</b><br><small>${c.symbol.toUpperCase()}</small></div></div></td><td>${usd(c.current_price)}</td><td class="${c.price_change_percentage_24h>=0?'positive':'negative'}">${pct(c.price_change_percentage_24h)}</td><td>${compact(c.market_cap)}</td><td>${compact(c.total_volume)}</td><td>${c.market_cap?(c.total_volume/c.market_cap).toFixed(2):'—'}</td><td class="negative">${pct(c.ath_change_percentage)}</td><td class="score">${c.score}</td><td><span class="badge ${cls}">${label}</span></td><td><button class="btn add-watch" data-id="${c.id}">+</button></td></tr>`}).join('');$$('.add-watch').forEach(b=>b.onclick=()=>addWatch(b.dataset.id));$('#scannerMessage').textContent=coins.length?`${coins.length} monedas cumplen los filtros actuales.`:'Ninguna moneda cumple los filtros o faltan datos.'}
function addWatch(id){if(!state.watchlist.includes(id)){state.watchlist.push(id);store.set('watchlist',state.watchlist);renderWatchlist()}}
function renderWatchlist(){const cards=state.watchlist.map(id=>{const c=state.market.get(id);if(!c)return `<article class="card watch-card"><div class="watch-head"><h3>${id}</h3><button class="remove" data-remove-watch="${id}">✕</button></div><p>Sin datos. Revisa que sea el ID correcto de CoinGecko.</p></article>`;return `<article class="card watch-card"><div class="watch-head"><div class="coin"><img src="${c.image}" alt=""><h3>${c.symbol.toUpperCase()}</h3></div><button class="remove" data-remove-watch="${id}">✕</button></div><div class="price">${usd(c.current_price)}</div><span class="${c.price_change_percentage_24h>=0?'positive':'negative'}">${pct(c.price_change_percentage_24h)} 24h</span><dl><div><dt>Market cap</dt><dd>${compact(c.market_cap)}</dd></div><div><dt>Volumen</dt><dd>${compact(c.total_volume)}</dd></div><div><dt>Vol/MCap</dt><dd>${c.market_cap?(c.total_volume/c.market_cap).toFixed(2):'—'}</dd></div><div><dt>Score</dt><dd>${scoreCoin(c)}/100</dd></div></dl></article>`}).join('');$('#watchCards').innerHTML=cards;$$('[data-remove-watch]').forEach(b=>b.onclick=()=>{state.watchlist=state.watchlist.filter(x=>x!==b.dataset.removeWatch);store.set('watchlist',state.watchlist);renderWatchlist()})}
function renderPortfolio(){let invested=0;$('#portfolioRows').innerHTML=state.portfolio.map((p,i)=>{const c=state.market.get(p.coinId),price=c?.current_price||0,value=price*p.balance,cost=p.entry*p.balance,pnl=value-cost,pnlPct=cost?pnl/cost*100:0;if(p.strategy==='Spot rápido'&&p.status!=='Cerrada')invested+=cost;return `<tr><td><b>${p.symbol}</b></td><td>${p.strategy}</td><td>${compact(p.balance)}</td><td>${usd(p.entry)}</td><td>${price?usd(price):'—'}</td><td>${price?usd(value):'—'}</td><td class="${pnl>=0?'positive':'negative'}">${price?`${usd(pnl)} (${pct(pnlPct)})`:'—'}</td><td>${p.target?`${p.target}% → ${usd(p.entry*(1+p.target/100))}`:'Bull run'}</td><td>${p.status}</td><td><button class="btn edit-position" data-i="${i}">Editar</button> <button class="remove delete-position" data-i="${i}">✕</button></td></tr>`}).join('');const budget=+$('#scalpBudgetInput').value||0;$('#investedTotal').textContent=usd(invested);$('#availableTotal').textContent=usd(Math.max(0,budget-invested));$('#scalpCapital').textContent=`${new Intl.NumberFormat('es-ES').format(budget)} USDT`;$('#capitalUsage').textContent=budget?`${Math.round(invested/budget*100)}% usado`:'Sin presupuesto';$$('.edit-position').forEach(b=>b.onclick=()=>openPosition(+b.dataset.i));$$('.delete-position').forEach(b=>b.onclick=()=>{state.portfolio.splice(+b.dataset.i,1);savePortfolio()})}
function openPosition(i=''){const p=i===''?{coinId:'',symbol:'',strategy:'Spot rápido',balance:'',entry:'',target:20,status:'Abierta'}:state.portfolio[i];$('#positionIndex').value=i;$('#positionCoinId').value=p.coinId;$('#positionSymbol').value=p.symbol;$('#positionStrategy').value=p.strategy;$('#positionBalance').value=p.balance;$('#positionEntry').value=p.entry;$('#positionTarget').value=p.target;$('#positionStatus').value=p.status;$('#positionDialog').showModal()}
function savePortfolio(){store.set('portfolio',state.portfolio);renderPortfolio()}
function renderJournal(){$('#journalRows').innerHTML=state.journal.map((j,i)=>`<tr><td>${j.date}</td><td>${j.coin}</td><td>${j.type}</td><td>${j.entry?usd(j.entry):'—'}</td><td>${j.exit?usd(j.exit):'—'}</td><td class="${j.result>=0?'positive':'negative'}">${j.result!==''?usd(+j.result):'—'}</td><td>${j.notes||''}</td><td><button class="remove delete-journal" data-i="${i}">✕</button></td></tr>`).join('');$$('.delete-journal').forEach(b=>b.onclick=()=>{state.journal.splice(+b.dataset.i,1);store.set('journal',state.journal);renderJournal()})}
function renderAll(){renderScanner();renderWatchlist();renderPortfolio();renderJournal()}
function setupTabs(){$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')})}
function setup(){setupTabs();$('#refreshBtn').onclick=refreshAll;$('#settingsBtn').onclick=()=>{$('#apiKeyInput').value=state.settings.apiKey;$('#refreshInterval').value=state.settings.interval;$('#settingsDialog').showModal()};$('#saveSettingsBtn').onclick=()=>{state.settings={apiKey:$('#apiKeyInput').value.trim(),interval:+$('#refreshInterval').value};store.set('settings',state.settings);schedule();setTimeout(refreshAll,100)};$('#watchlistForm').onsubmit=e=>{e.preventDefault();addWatch($('#coinIdInput').value.trim().toLowerCase());$('#coinIdInput').value='';refreshAll()};$('#addPositionBtn').onclick=()=>openPosition();$('#positionForm').onsubmit=e=>{e.preventDefault();const p={coinId:$('#positionCoinId').value.trim(),symbol:$('#positionSymbol').value.trim().toUpperCase(),strategy:$('#positionStrategy').value,balance:+$('#positionBalance').value,entry:+$('#positionEntry').value,target:+$('#positionTarget').value,status:$('#positionStatus').value};const i=$('#positionIndex').value;if(i==='')state.portfolio.push(p);else state.portfolio[+i]=p;$('#positionDialog').close();savePortfolio();refreshAll()};$('#addJournalBtn').onclick=()=>{$('#journalDate').value=new Date().toISOString().slice(0,10);$('#journalDialog').showModal()};$('#journalForm').onsubmit=e=>{e.preventDefault();state.journal.unshift({date:$('#journalDate').value,coin:$('#journalCoin').value,type:$('#journalType').value,entry:$('#journalEntry').value,exit:$('#journalExit').value,result:$('#journalResult').value,notes:$('#journalNotes').value});store.set('journal',state.journal);$('#journalDialog').close();e.target.reset();renderJournal()};$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#scalpBudgetInput').value=store.get('scalpBudget',1500);$('#scalpBudgetInput').oninput=e=>{store.set('scalpBudget',+e.target.value);renderPortfolio()};['maxMarketCap','minVolume','knownOnly'].forEach(id=>$('#'+id).oninput=renderScanner);$('#exportBtn').onclick=exportData;$('#importInput').onchange=importData;schedule();renderAll();refreshAll()}
function schedule(){if(state.timer)clearInterval(state.timer);if(state.settings.interval)state.timer=setInterval(refreshAll,state.settings.interval)}
function exportData(){const data={watchlist:state.watchlist,portfolio:state.portfolio,journal:state.journal,settings:{interval:state.settings.interval},scalpBudget:+$('#scalpBudgetInput').value};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='altcoin-radar-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.watchlist)state.watchlist=d.watchlist;if(d.portfolio)state.portfolio=d.portfolio;if(d.journal)state.journal=d.journal;if(d.scalpBudget!=null){$('#scalpBudgetInput').value=d.scalpBudget;store.set('scalpBudget',d.scalpBudget)}store.set('watchlist',state.watchlist);store.set('portfolio',state.portfolio);store.set('journal',state.journal);renderAll();refreshAll()}catch{alert('Archivo no válido')}};r.readAsText(f)}
document.addEventListener('DOMContentLoaded',setup);
