const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem('aor_'+k))??d}catch{return d}},set:(k,v)=>localStorage.setItem('aor_'+k,JSON.stringify(v))};
const state={watchlist:store.get('watchlist',APP_CONFIG.defaultWatchlist),portfolio:store.get('portfolio',APP_CONFIG.defaultPortfolio),journal:store.get('journal',[]),settings:store.get('settings',{apiKey:'',interval:0}),market:new Map(),fearHistory:[],btcHistory:[],timer:null,chartRange:0};
const usd=n=>Number.isFinite(+n)?new Intl.NumberFormat('es-ES',{style:'currency',currency:'USD',maximumFractionDigits:+n<0.01?8:2}).format(+n):'—';
const compact=n=>Number.isFinite(+n)?new Intl.NumberFormat('es-ES',{notation:'compact',maximumFractionDigits:2}).format(+n):'—';
const pct=n=>Number.isFinite(+n)?`${+n>=0?'+':''}${(+n).toFixed(2)}%`:'—';
function apiHeaders(){return state.settings.apiKey?{'x-cg-demo-api-key':state.settings.apiKey}:{} }
function coinIds(){return [...new Set([...APP_CONFIG.knownUniverse,...state.watchlist,...state.portfolio.map(p=>p.coinId),'bitcoin'])].filter(Boolean)}
async function fetchMarkets(){const ids=coinIds();const chunks=[];for(let i=0;i<ids.length;i+=150)chunks.push(ids.slice(i,i+150));const all=[];for(const chunk of chunks){const url=`https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${encodeURIComponent(chunk.join(','))}&order=market_cap_desc&per_page=250&page=1&sparkline=false&price_change_percentage=24h`;const r=await fetch(url,{headers:apiHeaders()});if(!r.ok)throw new Error(`CoinGecko ${r.status}`);all.push(...await r.json())}state.market=new Map(all.map(c=>[c.id,c]));return all}
async function fetchFear(){const r=await fetch('https://api.alternative.me/fng/?limit=0&format=json');if(!r.ok)throw new Error('Fear & Greed no disponible');const d=await r.json();state.fearHistory=(d.data||[]).map(x=>({value:+x.value,label:x.value_classification,ts:+x.timestamp*1000})).sort((a,b)=>a.ts-b.ts);return state.fearHistory}
async function fetchBtcHistory(){try{const r=await fetch('https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=usd&days=max&interval=daily',{headers:apiHeaders()});if(!r.ok)throw 0;const d=await r.json();state.btcHistory=(d.prices||[]).map(([ts,p])=>({ts,price:p}))}catch{state.btcHistory=[]}}
function fearClass(v){if(v<=24)return'Miedo extremo';if(v<=44)return'Miedo';if(v<=55)return'Neutral';if(v<=74)return'Codicia';return'Codicia extrema'}
function updateGauge(){const h=state.fearHistory,cur=h[h.length-1];if(!cur)return;const v=Math.max(0,Math.min(100,cur.value));$('#fearValue').textContent=v;$('#fearLabel').textContent=fearClass(v);$('#fearUpdated').textContent=new Date(cur.ts).toLocaleDateString('es-ES');$('#gaugeNeedle').style.transform=`rotate(${-90+v*1.8}deg)`;$('#gaugeProgress').style.strokeDashoffset=100-v;const itemFromDays=d=>h.reduce((best,x)=>Math.abs(x.ts-(Date.now()-d*864e5))<Math.abs((best?.ts||0)-(Date.now()-d*864e5))?x:best,null);[['fearYesterday',1],['fearWeek',7],['fearMonth',30]].forEach(([id,d])=>{const x=itemFromDays(d);$('#'+id).textContent=x?`${x.value} · ${fearClass(x.value)}`:'—'})}
function drawFearChart(){const cv=$('#fearChart'),ctx=cv.getContext('2d'),dpr=devicePixelRatio||1,w=cv.clientWidth,h=280;cv.width=w*dpr;cv.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);const cutoff=state.chartRange?Date.now()-state.chartRange*864e5:0;const f=state.fearHistory.filter(x=>x.ts>=cutoff),b=state.btcHistory.filter(x=>x.ts>=cutoff);if(f.length<2)return;ctx.strokeStyle='#323a4c';ctx.lineWidth=1;for(let i=0;i<=4;i++){const y=20+i*(h-45)/4;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-12,y);ctx.stroke();ctx.fillStyle='#8892a5';ctx.font='11px Inter';ctx.fillText(String(100-i*25),7,y+4)}const minTs=f[0].ts,maxTs=f[f.length-1].ts,x=ts=>40+(ts-minTs)/(maxTs-minTs)*(w-55),yF=v=>20+(100-v)/100*(h-45);const fearByTs=f;ctx.strokeStyle='#f4c84a';ctx.lineWidth=2.2;ctx.beginPath();fearByTs.forEach((p,i)=>{const X=x(p.ts),Y=yF(p.value);i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)});ctx.stroke();if(b.length){const minP=Math.min(...b.map(p=>p.price)),maxP=Math.max(...b.map(p=>p.price)),yB=p=>25+(maxP-p)/(maxP-minP||1)*(h-55);ctx.strokeStyle='#788397';ctx.lineWidth=1.8;ctx.beginPath();b.forEach((p,i)=>{if(p.ts<minTs||p.ts>maxTs)return;const X=x(p.ts),Y=yB(p.price);i?ctx.lineTo(X,Y):ctx.moveTo(X,Y)});ctx.stroke()}ctx.fillStyle='#8892a5';ctx.font='11px Inter';ctx.fillText(new Date(minTs).toLocaleDateString('es-ES',{month:'short',year:'2-digit'}),40,h-7);ctx.fillText(new Date(maxTs).toLocaleDateString('es-ES',{month:'short',year:'2-digit'}),w-75,h-7)}
function scoreCoin(c){let s=0;const ratio=c.market_cap?c.total_volume/c.market_cap:0;s+=Math.min(28,ratio*35);if(c.market_cap>5e6&&c.market_cap<150e6)s+=22;else if(c.market_cap<500e6)s+=10;if(c.total_volume>10e6)s+=20;else if(c.total_volume>2e6)s+=12;const ch=c.price_change_percentage_24h||0;if(ch>-8&&ch<12)s+=12;else if(ch>=12&&ch<30)s+=7;const ath=Math.abs(c.ath_change_percentage||0);if(ath>70&&ath<99)s+=12;else if(ath>50)s+=7;return Math.min(100,Math.round(s))}
function signal(score,c){if((c.total_volume||0)<500000)return['Riesgo extremo','red'];if(score>=78)return['Prioridad','green'];if(score>=62)return['Vigilar','blue'];if(score>=45)return['Esperar','yellow'];return['Débil','red']}
async function refreshAll(){try{$('#refreshBtn').textContent='Actualizando…';await Promise.all([fetchMarkets(),fetchFear(),fetchBtcHistory()]);updateGauge();renderAll();drawFearChart();const btc=state.market.get('bitcoin');$('#btcPrice').textContent=btc?usd(btc.current_price):'—';$('#btcChange').textContent=btc?pct(btc.price_change_percentage_24h):'—';$('#btcChange').className=(btc?.price_change_percentage_24h||0)>=0?'positive':'negative'}catch(e){console.error(e);alert('No se pudieron actualizar todos los datos. CoinGecko puede estar limitando peticiones; prueba de nuevo o añade una clave Demo en Ajustes.')}finally{$('#refreshBtn').textContent='Actualizar datos'}}
function renderPortfolio(){const long=state.portfolio.filter(p=>p.strategy==='Largo plazo'),scalp=state.portfolio.filter(p=>p.strategy==='Spot rápido');const summary={long:renderPortfolioTable(long,'longRows',false),scalp:renderPortfolioTable(scalp,'scalpRows',true)};const setPnl=(id,pnl,pctv)=>{const el=$(id);el.textContent=`${usd(pnl)} (${pct(pctv)})`;el.className=pnl>=0?'positive':'negative'};$('#longValue').textContent=usd(summary.long.value);setPnl('#longPnl',summary.long.pnl,summary.long.cost?summary.long.pnl/summary.long.cost*100:0);$('#longValueDetail').textContent=usd(summary.long.value);$('#longCost').textContent=usd(summary.long.cost);setPnl('#longPnlDetail',summary.long.pnl,summary.long.cost?summary.long.pnl/summary.long.cost*100:0);$('#scalpValue').textContent=usd(summary.scalp.value);setPnl('#scalpPnl',summary.scalp.pnl,summary.scalp.cost?summary.scalp.pnl/summary.scalp.cost*100:0);$('#scalpCost').textContent=usd(summary.scalp.cost);const budget=+$('#scalpBudgetInput').value||0,free=budget-summary.scalp.cost;$('#scalpAvailable').textContent=usd(free);$('#availableTotal').textContent=usd(free);$('#capitalUsage').textContent=budget?`${Math.round(summary.scalp.cost/budget*100)}% del presupuesto usado`:'Sin presupuesto'}
function renderPortfolioTable(list,tbodyId,isScalp){let value=0,cost=0;$('#'+tbodyId).innerHTML=list.map(p=>{const globalIndex=state.portfolio.indexOf(p),c=state.market.get(p.coinId),price=c?.current_price||0,v=price*p.balance,co=p.entry*p.balance,pnl=v-co,pnlPct=co?pnl/co*100:0;value+=v;cost+=co;const targetPrice=p.entry*(1+(p.target||0)/100);return `<tr><td><div class="coin-cell">${c?.image?`<img src="${c.image}" alt="">`:''}<b>${p.symbol}</b></div></td><td>${compact(p.balance)}</td><td>${usd(p.entry)}</td><td>${price?usd(price):'—'}</td><td>${price?usd(v):'—'}</td><td class="${pnl>=0?'positive':'negative'}">${price?`${usd(pnl)} (${pct(pnlPct)})`:'—'}</td><td>${p.target?`${p.target}%`:'Bull run'}</td>${isScalp?`<td>${p.target?usd(targetPrice):'—'}</td>`:''}<td>${p.status}</td><td><button class="btn edit-position" data-i="${globalIndex}">Editar</button> <button class="remove delete-position" data-i="${globalIndex}">✕</button></td></tr>`}).join('');return{value,cost,pnl:value-cost}}
function renderScanner(){const max=(+$('#maxMarketCap').value||150)*1e6,min=(+$('#minVolume').value||2)*1e6;const coins=APP_CONFIG.knownUniverse.map(id=>state.market.get(id)).filter(Boolean).filter(c=>c.market_cap<=max&&c.market_cap>=5e6&&c.total_volume>=min).map(c=>({...c,score:scoreCoin(c)})).sort((a,b)=>b.score-a.score);$('#scannerRows').innerHTML=coins.map((c,i)=>{const[label,cls]=signal(c.score,c);return `<tr><td>${i+1}</td><td><div class="coin-cell"><img src="${c.image}" alt=""><b>${c.symbol.toUpperCase()}</b></div></td><td>${usd(c.current_price)}</td><td class="${c.price_change_percentage_24h>=0?'positive':'negative'}">${pct(c.price_change_percentage_24h)}</td><td>${compact(c.market_cap)}</td><td>${compact(c.total_volume)}</td><td>${c.market_cap?(c.total_volume/c.market_cap).toFixed(2):'—'}</td><td class="negative">${pct(c.ath_change_percentage)}</td><td><b>${c.score}</b></td><td><span class="badge ${cls}">${label}</span></td><td><button class="btn add-watch" data-id="${c.id}">+</button></td></tr>`}).join('');$('#scannerMessage').textContent=`${coins.length} monedas cumplen los filtros.`;$$('.add-watch').forEach(b=>b.onclick=()=>addWatch(b.dataset.id))}
function addWatch(id){if(!state.watchlist.includes(id)){state.watchlist.push(id);store.set('watchlist',state.watchlist);renderWatchlist()}}
function renderWatchlist(){$('#watchCards').innerHTML=state.watchlist.map(id=>{const c=state.market.get(id);if(!c)return`<article class="card watch-card"><div class="watch-head"><h3>${id}</h3><button class="remove" data-remove-watch="${id}">✕</button></div><p>Sin datos. Comprueba el ID de CoinGecko.</p></article>`;return`<article class="card watch-card"><div class="watch-head"><div class="coin"><img src="${c.image}" alt=""><h3>${c.symbol.toUpperCase()}</h3></div><button class="remove" data-remove-watch="${id}">✕</button></div><div class="price">${usd(c.current_price)}</div><span class="${c.price_change_percentage_24h>=0?'positive':'negative'}">${pct(c.price_change_percentage_24h)} 24h</span><dl><div><dt>Market cap</dt><dd>${compact(c.market_cap)}</dd></div><div><dt>Volumen</dt><dd>${compact(c.total_volume)}</dd></div><div><dt>Vol/MCap</dt><dd>${c.market_cap?(c.total_volume/c.market_cap).toFixed(2):'—'}</dd></div><div><dt>Score</dt><dd>${scoreCoin(c)}/100</dd></div></dl></article>`}).join('');$$('[data-remove-watch]').forEach(b=>b.onclick=()=>{state.watchlist=state.watchlist.filter(x=>x!==b.dataset.removeWatch);store.set('watchlist',state.watchlist);renderWatchlist()})}
function openPosition(i='',strategy='Largo plazo'){const p=i===''?{coinId:'',symbol:'',strategy,balance:'',entry:'',target:strategy==='Spot rápido'?20:0,status:'Abierta'}:state.portfolio[i];$('#positionIndex').value=i;$('#positionCoinId').value=p.coinId;$('#positionSymbol').value=p.symbol;$('#positionStrategy').value=p.strategy;$('#positionBalance').value=p.balance;$('#positionEntry').value=p.entry;$('#positionTarget').value=p.target;$('#positionStatus').value=p.status;$('#positionDialog').showModal()}
function renderJournal(){$('#journalRows').innerHTML=state.journal.map((j,i)=>`<tr><td>${j.date}</td><td>${j.coin}</td><td>${j.type}</td><td>${j.entry?usd(j.entry):'—'}</td><td>${j.exit?usd(j.exit):'—'}</td><td class="${+j.result>=0?'positive':'negative'}">${j.result!==''?usd(+j.result):'—'}</td><td>${j.notes||''}</td><td><button class="remove delete-journal" data-i="${i}">✕</button></td></tr>`).join('');$$('.delete-journal').forEach(b=>b.onclick=()=>{state.journal.splice(+b.dataset.i,1);store.set('journal',state.journal);renderJournal()})}
function renderAll(){renderPortfolio();renderScanner();renderWatchlist();renderJournal()}
function setupTabs(){$$('.tab').forEach(t=>t.onclick=()=>{$$('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#'+t.dataset.tab).classList.add('active')})}
function exportData(){const data={watchlist:state.watchlist,portfolio:state.portfolio,journal:state.journal,settings:{interval:state.settings.interval},scalpBudget:+$('#scalpBudgetInput').value};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='altcoin-radar-backup.json';a.click();URL.revokeObjectURL(a.href)}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(d.watchlist)state.watchlist=d.watchlist;if(d.portfolio)state.portfolio=d.portfolio;if(d.journal)state.journal=d.journal;if(d.scalpBudget!=null){$('#scalpBudgetInput').value=d.scalpBudget;store.set('scalpBudget',d.scalpBudget)}store.set('watchlist',state.watchlist);store.set('portfolio',state.portfolio);store.set('journal',state.journal);renderAll();refreshAll()}catch{alert('Archivo no válido')}};r.readAsText(f)}
function schedule(){if(state.timer)clearInterval(state.timer);if(state.settings.interval)state.timer=setInterval(refreshAll,state.settings.interval)}
function setup(){setupTabs();$('#refreshBtn').onclick=refreshAll;$('#settingsBtn').onclick=()=>{$('#apiKeyInput').value=state.settings.apiKey;$('#refreshInterval').value=state.settings.interval;$('#settingsDialog').showModal()};$('#saveSettingsBtn').onclick=()=>{state.settings={apiKey:$('#apiKeyInput').value.trim(),interval:+$('#refreshInterval').value};store.set('settings',state.settings);schedule();setTimeout(refreshAll,100)};$('#watchlistForm').onsubmit=e=>{e.preventDefault();addWatch($('#coinIdInput').value.trim().toLowerCase());$('#coinIdInput').value='';refreshAll()};$$('.add-position').forEach(b=>b.onclick=()=>openPosition('',b.dataset.strategy));$('#positionForm').onsubmit=e=>{e.preventDefault();const p={coinId:$('#positionCoinId').value.trim().toLowerCase(),symbol:$('#positionSymbol').value.trim().toUpperCase(),strategy:$('#positionStrategy').value,balance:+$('#positionBalance').value,entry:+$('#positionEntry').value,target:+$('#positionTarget').value,status:$('#positionStatus').value};const i=$('#positionIndex').value;if(i==='')state.portfolio.push(p);else state.portfolio[+i]=p;store.set('portfolio',state.portfolio);$('#positionDialog').close();renderPortfolio();refreshAll()};document.body.addEventListener('click',e=>{const ed=e.target.closest('.edit-position'),del=e.target.closest('.delete-position');if(ed)openPosition(+ed.dataset.i);if(del){state.portfolio.splice(+del.dataset.i,1);store.set('portfolio',state.portfolio);renderPortfolio()}});$('#addJournalBtn').onclick=()=>{$('#journalDate').value=new Date().toISOString().slice(0,10);$('#journalDialog').showModal()};$('#journalForm').onsubmit=e=>{e.preventDefault();state.journal.unshift({date:$('#journalDate').value,coin:$('#journalCoin').value,type:$('#journalType').value,entry:$('#journalEntry').value,exit:$('#journalExit').value,result:$('#journalResult').value,notes:$('#journalNotes').value});store.set('journal',state.journal);$('#journalDialog').close();e.target.reset();renderJournal()};$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#scalpBudgetInput').value=store.get('scalpBudget',1500);$('#scalpBudgetInput').oninput=e=>{store.set('scalpBudget',+e.target.value);renderPortfolio()};['maxMarketCap','minVolume'].forEach(id=>$('#'+id).oninput=renderScanner);$$('.range-btn').forEach(b=>b.onclick=()=>{$$('.range-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.chartRange=+b.dataset.range;drawFearChart()});$('#exportBtn').onclick=exportData;$('#importInput').onchange=importData;window.addEventListener('resize',()=>requestAnimationFrame(drawFearChart));schedule();renderAll();refreshAll()}
document.addEventListener('DOMContentLoaded',setup);
